version: "3.9"
services:
  postgres:
    image: 'postgres'
    ports: 
      - '5434:5432'
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - ./env/postgres.env

volumes:
  data: