upstream api {
    server backend:8010;
}

server {
    listen 8080;
    server_name thinkschoolpsych.com www.thinkschoolpsych.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 default_server ssl http2;
    listen [::]:443 ssl http2;

    server_name thinkschoolpsych.com www.thinkschoolpsych.com;

    ssl_certificate /etc/nginx/ssl/live/thinkschoolpsych.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/thinkschoolpsych.com/privkey.pem;
    
    index index.html index.htm;

    location / {
        root /var/www/html;
    }

    location /api/ {
        # address "backend" is set by docker-compose
        proxy_pass http://api;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_hide_header 'Access-Control-Allow-Origin';
        proxy_cache_bypass $http_upgrade;
    }

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
}