server {
    listen 8080;

    location / {
        root /var/www/html;
    }

    location /api/ {
        # address "backend" is set by docker-compose
        proxy_pass http://backend:8010/;
    }
}